name: amazon_cognito_identity_dart
version: 0.0.22
homepage: https://github.com/jonsaw/amazon-cognito-identity-dart/tree/master
description: Unofficial Amazon Cognito Identity Provider Dart SDK,
  to easily add user sign-up and sign-in to your mobile and web apps
  with AWS Cloud Services.

dependencies:
  crypto: ^3.0.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.1

environment:
  sdk: ">=2.11.0 <3.0.0"
